FROM amazoncorretto:11-alpine3.17

# Create user
RUN adduser -h /petclinic -s /bin/sh -D petclinic

# Create directory
RUN mkdir -p /petclinic && chown petclinic:petclinic /petclinic

# Add JAR from working link
ADD --chown=petclinic:petclinic \
  https://repo.spring.io/release/org/springframework/samples/spring-petclinic/2.4.2/spring-petclinic-2.4.2.jar \
  /petclinic/spring-petclinic-2.4.2.jar

USER petclinic
WORKDIR /petclinic

CMD ["java", "-jar", "spring-petclinic-2.4.2.jar"]
